spring:
  profiles:
    active:
      - dev
  config:
    import: optional:file:.env[.properties]

springdoc:
  swagger-ui:
    enabled: true
    path:
      - /swagger-ui.html
  api-docs:
    path:
      - /v3/api-docs

portone:
  store-id: ${PORTONE_STORE_ID}
  channel-key: ${PORTONE_CHANNEL_KEY}
  api-secret: ${PORTONE_API_SECRET}