spring:
  profiles:
    active:
      - dev
  config:
    import: optional:file:.env[.properties]

springdoc:
  swagger-ui:
    enabled: true
    path:
      - /swagger-ui.html
  api-docs:
    path:
      - /v3/api-docs

portone:
  store-id: ${PORTONE_STORE_ID}
  channel-key: ${PORTONE_CHANNEL_KEY}
  api-secret: ${PORTONE_API_SECRET}
  
oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    admin-key: ${KAKAO_ADMIN_KEY}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}

catchcatch:
  key: ${CATCHCATCH_KEY}

sol:
  key: ${SOL_API_KEY}
  secret: ${SOL_API_SECRET}
  sender: ${SOL_SENDER}

