server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
    encoding:
      charset: utf-8
      force: true
  tomcat:
    # 부하 테스트 용도
    threads:
      max: 400
      min-spare: 50
    accept-count: 200
    max-connections: 10000

# log 설정
logging:
  level:
    root: INFO
    com.tenco: DEBUG
    # JPA Repository를 Redis Repository로도 잡을 수 있다는 안내성 경고가
    # data-redis 의존성 추가로 모든 Repository에 대해 출력되어 로그가 지저분해지는 것을 방지
    org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport: ERROR

# mustache 설정
spring:
  mustache:
    servlet:
      expose-session-attributes: false
      expose-request-attributes: true

  # 이메일 발송 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER}
    password: ${GOOGLE_APP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


  #데이터베이스 연결 설정 (MySQL)
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Seoul
    #    username:
    #    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
    hikari:
      # 부하 테스트 용도
      maximum-pool-size: 100
      minimum-idle: 20
      connection-timeout: 10000
  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always  # 외부 DB(MySQL)에서도 실행되도록 설정
      data-locations:
        - classpath:db/data.sql

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

  data:
    redis:
      host: localhost
      port: 6379